---
apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/parameter_substitution: 'true'
  namespace: jenkins
  name: parameter_substitution
spec:
  containers:
  - name: ruby
    image: ruby:2.6.5
    tty: true
    resources:
      requests:
        memory: "100Mi"
    command:
      - cat
