---
name: Unit Tests
on: [push, pull_request]
jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.1, 3.2, 3.3, 3.4]
        gemfile:
        - Gemfile
        - gemfiles/activesupport_7_0.gemfile
        - gemfiles/activesupport_7_1.gemfile
        - gemfiles/activesupport_7_2.gemfile
        - gemfiles/activesupport_8_0.gemfile
        exclude:
        - ruby: 3.1
          gemfile: gemfiles/activesupport_8_0.gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: 2.3.9
        bundler-cache: true
    - run: bundle exec rspec
