---
name: Unit Tests
on: [push, pull_request]
jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gemfile:
        - Gemfile
        - gemfiles/rails_5.gemfile
        - gemfiles/rails_6.gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.5
        bundler: 1.17.3
        bundler-cache: true
    - run: bundle exec rspec
